# Generated by Django 4.0.2 on 2022-02-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('sub_titulo', models.CharField(max_length=200)),
                ('data_do_post', models.DateField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='posts')),
            ],
        ),
    ]
